services:
  mongodb:
    image: mongo:4.4.6
    restart: unless-stopped
    container_name: 'mongodb' 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: generic
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=generic
      - ME_CONFIG_MONGODB_URL=mongodb://root:generic@mongodb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongodb
    restart: unless-stopped
    ports:
      - "8082:8081"
volumes:
  mongodb-data:
